
name: 'aqi_dbt'
version: '0.0.1'
config-version: 2

profile: 'aqi_dbt'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"


models:
  aqi_dbt:
    base:
      +materialized: ephemeral
