
name: 'aqi_dbt'
version: '0.0.1'
config-version: 2

profile: 'aqi_dbt'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"


seeds:
  aqi_dbt:
    seed_sites_msa_mapping:
      +column_types:
        site_id: string
        msa_code: string
        msa_name: string